osx_image: xcode8
language: objective-c
xcode_project: STHAL.xcodeproj
matrix:
    include:
        - xcode_sdk: iphonesimulator7.1
          xcode_scheme: STHAL-ios
        - xcode_sdk: iphonesimulator8.1
          xcode_scheme: STHAL-ios
        - xcode_sdk: macosx
          xcode_scheme: STHAL-mac
branches:
    only:
        - master
before_script:
    - gem install xcpretty
script: xcodebuild -project ${TRAVIS_XCODE_PROJECT} -scheme ${TRAVIS_XCODE_SCHEME} -sdk ${TRAVIS_XCODE_SDK} | xcpretty
